In [54]:
# Use this url: https://results.isu.org/events

import pandas as pd

url = "https://results.isu.org/events/csusa12025_Women.htm?utm_source=chatgpt.com"
tables = pd.read_html(url)
df = tables[0]
df.to_csv("isu_scores.csv", index=False)

In [55]:
data = pd.read_csv('isu_scores.csv')
data.head()

      0                  1       2       3    4    5
0   NaN                NaN     NaN     NaN  NaN  NaN
1  Rank               Name  Nation  Points   SP   FS
2     1     Isabeau LEVITO     USA  207.61    1    2
3     2  Sofia SAMODELKINA     KAZ  203.15    2    1
4     3           Jia SHIN     KOR  179.97    3    3

In [56]:
# Remove nulls from header
data = data.iloc[1:].reset_index(drop=True)
data.head()

      0                  1       2       3   4   5
0  Rank               Name  Nation  Points  SP  FS
1     1     Isabeau LEVITO     USA  207.61   1   2
2     2  Sofia SAMODELKINA     KAZ  203.15   2   1
3     3           Jia SHIN     KOR  179.97   3   3
4     4       Sonja HILMER     USA  165.83   4   4

In [57]:
# Make the first row the column names
data.columns = data.iloc[0]
data = data[1:].reset_index(drop=True)
data.head()

0 Rank               Name Nation  Points SP FS
0    1     Isabeau LEVITO    USA  207.61  1  2
1    2  Sofia SAMODELKINA    KAZ  203.15  2  1
2    3           Jia SHIN    KOR  179.97  3  3
3    4       Sonja HILMER    USA  165.83  4  4
4    5      Josephine LEE    USA  160.99  5  5

In [58]:
# Now let's get scores from each of the skaters individually
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.isuresults.com/bios/isufs00111287.htm"

r = requests.get(url)
soup = BeautifulSoup(r.text, "html.parser")

name = soup.find(text=lambda t: t and t.strip().istitle())

lines = [line.strip() for line in soup.text.split("\n") if line.strip()]

lines

/var/folders/8t/bwgvq_w97yd84srzdk9kxpkc0000gn/T/ipykernel_55073/417929609.py:11: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  name = soup.find(text=lambda t: t and t.strip().istitle())

['Women',
 'Date of birth:',
 '03.03.2007',
 'Isabeau LEVITO',
 'Place of birth:',
 'Philadelphia, PA',
 'Height:',
 '160 cm',
 'USA',
 'Home town:',
 'Mount Holly, NJ',
 'Profession:',
 'high school student',
 'Hobbies:',
 'reading',
 'Start sk. / Club:',
 '2010 / Skating Club of Southern NJ',
 'Internet / Social Media contact:',
 'Instagram: isabeau.levito',
 'Coach:',
 'Julia Kuznetsova, Otar Japaridze, Slava Kuznetsov',
 'Choreographer:',
 'Julia Kuznetsova, Otar Japaridze',
 'Practice low season:',
 'h/week\xa0Mount Laurel, NJ',
 'Practice high season:',
 'h/week\xa0Mount Laurel, NJ',
 'Music Short Program as of season 2025/2026',
 'Almost In Your Arms (from "Houseboat" soundtrack) by Sophia Loren, Jay Livingston, Ray Evans Zou Bisou Bisou (from "The Millionaires" soundtrack) by Sophia Loren, Bill Shepherd, Alan Tew',
 'Music Free Skating / Free Dance as of season 2025/2026',
 'Cinema Paradiso by Ennio Morricone',
 'Personal Best Total Score',
 '215.74',
 '13.11.2022',
 'ISU GP MK John Wilson Trophy 2022',
 'Personal Best Score Short Program',
 '73.73',
 '20.03.2024',
 'ISU World Championships 2024',
 'Personal Best Score Free Skating',
 '143.68',
 '13.11.2022',
 'ISU GP MK John Wilson Trophy 2022',
 'Season Best Total Score',
 '212.71',
 '18.10.2025',
 'ISU GP Grand Prix de France 2025',
 'Season Best Score Short Program',
 '73.37',
 '17.10.2025',
 'ISU GP Grand Prix de France 2025',
 'Season Best Score Free Skating',
 '139.34',
 '18.10.2025',
 'ISU GP Grand Prix de France 2025',
 '18/19',
 '19/20',
 '20/21',
 '21/22',
 '22/23',
 '23/24',
 '24/25',
 '25/26',
 'Olympic Games',
 'World Championship',
 '4',
 '2',
 '4',
 'European Championship',
 'Four Continents',
 'World Juniors',
 '1',
 'National Championship',
 '3.S',
 '1.S',
 '3.S',
 '3.S',
 'S=Senior; J=Junior; N=Novice',
 'International Competition',
 'Year',
 'Place',
 'International Competition',
 'Year',
 'Place',
 'ISU CS Cranberry Cup International 2024, Norwood, MA',
 '2024',
 '3.',
 'ISU CS Cranberry Cup International 2025, Norwood, MA',
 '2025',
 '1.',
 'ISU CS Nebelhorn Trophy 2024, Oberstdorf',
 '2024',
 '2.',
 'ISU CS Nebelhorn Trophy 2025, Oberstdorf',
 '2025',
 '4.',
 'ISU GP Skate America 2024, Allen, TX',
 '2024',
 '3.',
 'ISU GP Grand Prix de France 2025, Angers',
 '2025',
 '4.',
 'Road to 26 Trophy (OWG test event), Assago (MI)',
 '2025',
 '2.',
 'ISU GP Skate Canada International 2025, Saskatoon',
 '2025',
 '2.',
 'Levito started skating after watching the 2010 Olympic Winter Games. She has family roots from Milan, Italy and speaks Italian. Levito won the ISU Skating Award in the category "Best Newcomer" in 2023. She missed part of the 2024/25 season as she recovered from injury.',
 'Personal Bests | Competition Results | Privacy Policy',
 '© copyright by: International Skating Union, Avenue Juste-Olivier 17, CH - 1006 Lausanne',
 '02/02/2026 19:21:11 UTC',
 "<td class = 'flx20"]

In [59]:
# This doesn't give us much insight on her individual scores --> it just details personal best and her biographical details
# Let's look at the first table again

In [60]:
# We could continue cleaning this but this data also doesn't give us a lot of information on the scoring... it just gives overall scores 
# short program and free skate

In [61]:
pip install "camelot-py[cv]"

Requirement already satisfied: camelot-py[cv] in /opt/anaconda3/lib/python3.13/site-packages (1.0.9)
WARNING: camelot-py 1.0.9 does not provide the extra 'cv'
Requirement already satisfied: click>=8.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from camelot-py[cv]) (8.1.8)
Requirement already satisfied: chardet>=5.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from camelot-py[cv]) (5.2.0)
Requirement already satisfied: numpy>=1.26.1 in /opt/anaconda3/lib/python3.13/site-packages (from camelot-py[cv]) (2.1.3)
Requirement already satisfied: openpyxl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from camelot-py[cv]) (3.1.5)
Requirement already satisfied: pdfminer-six>=20240706 in /opt/anaconda3/lib/python3.13/site-packages (from camelot-py[cv]) (20251230)
Requirement already satisfied: pypdf<6.0,>=4.0 in /opt/anaconda3/lib/python3.13/site-packages (from camelot-py[cv]) (5.9.0)
Requirement already satisfied: pandas>=2.2.2 in /opt/anaconda3/lib/python3.13/site-packages (from camelot-py[cv]) (2.2.3)
Requirement already satisfied: tabulate>=0.9.0 in /opt/anaconda3/lib/python3.13/site-packages (from camelot-py[cv]) (0.9.0)
Requirement already satisfied: opencv-python-headless>=4.7.0.68 in /opt/anaconda3/lib/python3.13/site-packages (from camelot-py[cv]) (4.13.0.92)
Requirement already satisfied: pypdfium2>=4 in /opt/anaconda3/lib/python3.13/site-packages (from camelot-py[cv]) (5.4.0)
Requirement already satisfied: pillow>=10.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from camelot-py[cv]) (11.1.0)
Requirement already satisfied: et_xmlfile in /opt/anaconda3/lib/python3.13/site-packages (from openpyxl>=3.1.0->camelot-py[cv]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=2.2.2->camelot-py[cv]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=2.2.2->camelot-py[cv]) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=2.2.2->camelot-py[cv]) (2025.2)
Requirement already satisfied: charset-normalizer>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from pdfminer-six>=20240706->camelot-py[cv]) (3.3.2)
Requirement already satisfied: cryptography>=36.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from pdfminer-six>=20240706->camelot-py[cv]) (44.0.1)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography>=36.0.0->pdfminer-six>=20240706->camelot-py[cv]) (1.17.1)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer-six>=20240706->camelot-py[cv]) (2.21)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=2.2.2->camelot-py[cv]) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [62]:
import camelot
import pandas as pd

pdf_path = "BostonMASkatingChamps.pdf"

tables = camelot.read_pdf(pdf_path, pages="all", flavor="lattice")

print("Tables found:", tables.n)

Tables found: 0

In [63]:
tables = camelot.read_pdf(pdf_path, pages="all", flavor="stream")

print("Tables found:", tables.n)

Tables found: 17

In [64]:
# ok stream works, lets inspect them
for i, table in enumerate(tables):
    print(f"\n--- TABLE {i} ---")
    print(table.df.head())

--- TABLE 0 ---
                    0             1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                   Starting
2                 Rank          Name     Nation
3                                                     Number
4                       1\nAlysa LIU        USA           18

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          74.58             40.80

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             33.78                 0.00

--- TABLE 1 ---
                    0                  1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                        Starting
2                 Rank               Name     Nation
3                                                          Number
4                       3\nIsabeau LEVITO        USA           31

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          73.33             39.27

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             34.06                 0.00

--- TABLE 2 ---
                    0                  1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                        Starting
2                 Rank               Name     Nation
3                                                          Number
4                       5\nKaori SAKAMOTO        JPN           32

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          71.03             35.99

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             35.04                 0.00

--- TABLE 3 ---
                    0             1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                   Starting
2                 Rank          Name     Nation
3                                                     Number
4                       7\nHaein LEE        KOR           22

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          67.79             36.89

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             30.90                 0.00

--- TABLE 4 ---
                    0               1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                     Starting
2                 Rank            Name     Nation
3                                                       Number
4                       9\nAmber GLENN        USA           30

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          67.65             35.91

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             32.74                -1.00

--- TABLE 5 ---
                    0                 1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                       Starting
2                 Rank              Name     Nation
3                                                         Number
4                       11\nChaeyeon KIM        KOR           33

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          65.67             34.81

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             31.86                -1.00

--- TABLE 6 ---
                    0                      1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                            Starting
2                 Rank                   Name     Nation
3                                                              Number
4                       13\nSofia SAMODELKINA        KAZ           10

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          63.58             34.69

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             28.89                 0.00

--- TABLE 7 ---
                    0                  1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                        Starting
2                 Rank               Name     Nation
3                                                          Number
4                       15\nLorine SCHILD        FRA           20

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          60.59             33.42

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             27.17                 0.00

--- TABLE 8 ---
                    0                  1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                        Starting
2                 Rank               Name     Nation
3                                                          Number
4                       17\nOlga MIKUTINA        AUT           13

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          59.63             31.03

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             28.60                 0.00

--- TABLE 9 ---
                    0                  1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                        Starting
2                 Rank               Name     Nation
3                                                          Number
4                       19\nMariia SENIUK        ISR           15

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          56.96             31.69

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             25.27                 0.00

--- TABLE 10 ---
                    0                       1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                             Starting
2                 Rank                    Name     Nation
3                                                               Number
4                       21\nEkaterina KURAKOVA        POL           24

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          55.52             26.83

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             28.69                 0.00

--- TABLE 11 ---
                    0                 1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                       Starting
2                 Rank              Name     Nation
3                                                         Number
4                       23\nLivia KAISER        SUI           16

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          53.68             27.62

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             26.06                 0.00

--- TABLE 12 ---
                    0                        1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                              Starting
2                 Rank                     Name     Nation
3                                                                Number
4                       25\nNargiz SUELEYMANOVA        AZE            1

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          50.97             28.41

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             22.56                 0.00

--- TABLE 13 ---
                    0               1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                     Starting
2                 Rank            Name     Nation
3                                                       Number
4                       27\nXiangyi AN        CHN            7

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          47.52             24.54

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             23.98                -1.00

--- TABLE 14 ---
                    0                   1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                         Starting
2                 Rank                Name     Nation
3                                                           Number
4                       29\nMia RISA GOMEZ        NOR            8

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          46.43             22.68

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             23.75                 0.00

--- TABLE 15 ---
                    0              1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                    Starting
2                 Rank           Name     Nation
3                                                      Number
4                       31\nAhsun YUN        KOR            9

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          41.08             19.94

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             23.14                -2.00

--- TABLE 16 ---
                    0                     1  2       3  4         5  6   \
0  WOMEN SHORT PROGRAM
1                                                           Starting
2                 Rank                  Name     Nation
3                                                             Number
4                       33\nAnastasia GOZHVA        UKR            4

              7  8              9  10                       11  \
0
1  Total Segment     Total Element     Total Program Component
2
3          Score             Score
4          37.54             20.05

                 12 13                14
0
1
2                       Total Deductions
3  Score (factored)
4             19.49                -2.00

In [65]:
# this only gives me the top table again, not the actual scoring

In [66]:
pip install pdfplumber

Requirement already satisfied: pdfplumber in /opt/anaconda3/lib/python3.13/site-packages (0.11.9)
Requirement already satisfied: pdfminer.six==20251230 in /opt/anaconda3/lib/python3.13/site-packages (from pdfplumber) (20251230)
Requirement already satisfied: Pillow>=9.1 in /opt/anaconda3/lib/python3.13/site-packages (from pdfplumber) (11.1.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /opt/anaconda3/lib/python3.13/site-packages (from pdfplumber) (5.4.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from pdfminer.six==20251230->pdfplumber) (3.3.2)
Requirement already satisfied: cryptography>=36.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from pdfminer.six==20251230->pdfplumber) (44.0.1)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.21)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [67]:
import pdfplumber

text = ""

with pdfplumber.open("BostonMASkatingChamps.pdf") as pdf:
    for page in pdf.pages:
        text += page.extract_text() + "\n"

print(text[:2000])  # inspect first part

JUDGES DETAILS PER SKATER
WOMEN SHORT PROGRAM
Starting Total Segment Total Element Total Program Component
Rank Name Nation Total Deductions
Number Score Score Score (factored)
1 Alysa LIU USA 18 74.58 40.80 33.78 0.00
# Executed Elements
printed: 26.03.2025 16:48
ofnI Base Scores of GOE J1 J2 J3 J4 J5 J6 J7 J8 J9 Ref.
Value Panel
1 3F+3T 9.50 1.14 2 2 2 3 2 2 2 3 2 10.64
2 2A 3.30 0.90 3 3 2 2 3 3 3 3 2 4.20
3 CCoSp4 3.50 1.05 3 3 3 3 3 3 3 3 3 4.55
4 3Lz 6.49 x 1.43 3 2 2 3 2 2 2 3 3 7.92
5 FCSp4 3.20 1.14 4 4 3 4 2 4 4 3 3 4.34
6 StSq4 3.90 1.39 4 4 4 3 3 3 3 4 4 5.29
7 LSp4 2.70 1.16 5 4 4 3 4 4 5 5 4 3.86
32.59 40.80
Program Components Factor
Composition 1.33 9.00 8.50 8.25 7.75 8.75 8.25 8.25 8.50 8.50 8.43
Presentation 1.33 9.00 9.25 8.50 8.50 9.00 8.50 8.50 8.50 8.75 8.68
Skating Skills 1.33 8.75 8.50 8.00 7.75 8.50 8.25 8.25 8.25 8.25 8.29
Judges Total Program Component Score (factored) 33.78
Deductions: 0.00
Starting Total Segment Total Element Total Program Component
Rank Name Nation Total Deductions
Number Score Score Score (factored)
2 Mone CHIBA JPN 26 73.44 39.34 34.10 0.00
# Executed Elements ofnI Base Scores of GOE J1 J2 J3 J4 J5 J6 J7 J8 J9 Ref.
Value Panel
1 3Lz+3Tq q 10.10 0.51 0 1 0 3 3 1 -1 0 1 10.61
2 2A 3.30 0.94 2 3 2 3 3 3 3 4 3 4.24
3 FCSp4 3.20 0.87 3 3 2 2 1 4 3 3 3 4.07
4 3F 5.83 x 1.59 3 3 3 4 3 3 3 3 3 7.42
5 CCoSp4 3.50 1.05 3 3 3 3 3 4 3 3 3 4.55
6 StSq3 3.30 1.18 3 3 3 4 4 4 3 4 4 4.48
7 LSp4 2.70 1.27 5 4 4 4 5 5 5 5 5 3.97
31.93 39.34
Program Components Factor
Composition 1.33 8.50 8.25 8.50 8.25 8.25 8.75 8.50 9.00 8.50 8.46
Presentation 1.33 8.50 8.75 8.50 8.25 8.50 8.75 8.25 9.00 8.50 8.54
Skating Skills 1.33 8.75 8.75 8.50 8.50 9.00 8.50 8.50 8.75 8.75 8.64
Judges Total Program Component Score (factored) 34.10
Deductions: 0.00
Page 1 / 17
JUDGES DETAILS PER SKATER
WOMEN SHORT PROGRAM
Starting Total Segment Total Element Total Program Component
Rank Name Nation Total Deductions
Number Score Score Score (factored)
3 Isabeau LEV

In [68]:
# Ok now i get all scores for the skaters, lets turn this into a dataframe
import re
import pandas as pd

skater_blocks = text.split("Rank Name Nation")

all_elements = []

for block in skater_blocks[1:]:
    
    # --- Extract skater name ---
    name_match = re.search(r"\d+\s+([A-Za-z\s\-']+)\s+[A-Z]{3}", block)
    if not name_match:
        continue
    
    skater_name = name_match.group(1).strip()
    
    # --- Extract elements ---
    element_pattern = re.compile(
        r"\n\s*(\d+)\s+([A-Za-z0-9\+\*q<>]+)\s+([\d\.]+)\s+([\d\.\-]+).*?([\d\.]+)$",
        re.MULTILINE
    )
    
    for match in element_pattern.finditer(block):
        all_elements.append({
            "Skater": skater_name,
            "Element #": match.group(1),
            "Element": match.group(2),
            "Base Value": float(match.group(3)),
            "GOE": float(match.group(4)),
            "Final Score": float(match.group(5))
        })

elements_df = pd.DataFrame(all_elements)

elements_df.head()

      Skater Element # Element  Base Value   GOE  Final Score
0  Alysa LIU         1   3F+3T         9.5  1.14        10.64
1  Alysa LIU         2      2A         3.3  0.90         4.20
2  Alysa LIU         3  CCoSp4         3.5  1.05         4.55
3  Alysa LIU         5   FCSp4         3.2  1.14         4.34
4  Alysa LIU         6   StSq4         3.9  1.39         5.29

In [69]:
# Yes, this works! Note, this is only GOE, not any of the subjective based scoring
# Let's look at the parts for alysa LIU

elements_df.loc[elements_df['Skater']=='Alysa LIU',:]

      Skater Element # Element  Base Value   GOE  Final Score
0  Alysa LIU         1   3F+3T         9.5  1.14        10.64
1  Alysa LIU         2      2A         3.3  0.90         4.20
2  Alysa LIU         3  CCoSp4         3.5  1.05         4.55
3  Alysa LIU         5   FCSp4         3.2  1.14         4.34
4  Alysa LIU         6   StSq4         3.9  1.39         5.29
5  Alysa LIU         7    LSp4         2.7  1.16         3.86

In [70]:
# Let's do this for the subjective scoring portion:

In [71]:
pcs_rows = []

for block in skater_blocks[1:]:
    
    # --- Extract skater name ---
    name_match = re.search(r"\d+\s+([A-Za-z\s\-']+)\s+[A-Z]{3}", block)
    if not name_match:
        continue
    
    skater_name = name_match.group(1).strip()
    
    # --- Extract PCS lines ---
    pcs_pattern = re.compile(
        r"(Composition|Presentation|Skating Skills)\s+([\d\.]+)\s+((?:\d+\.\d+\s+){8,9})(\d+\.\d+)"
    )
    
    for match in pcs_pattern.finditer(block):
        
        component = match.group(1)
        factor = float(match.group(2))
        
        # Judge scores
        judge_scores = match.group(3).strip().split()
        
        # Last value = panel average
        panel_avg = float(match.group(4))
        
        for i, score in enumerate(judge_scores):
            pcs_rows.append({
                "Skater": skater_name,
                "Component": component,
                "Judge": f"J{i+1}",
                "Score": float(score),
                "Factor": factor,
                "Panel Avg": panel_avg
            })

In [72]:
pcs_df = pd.DataFrame(pcs_rows)
pcs_df.loc[pcs_df['Skater']=='Alysa LIU',:]

       Skater       Component Judge  Score  Factor  Panel Avg
0   Alysa LIU     Composition    J1   9.00    1.33       8.43
1   Alysa LIU     Composition    J2   8.50    1.33       8.43
2   Alysa LIU     Composition    J3   8.25    1.33       8.43
3   Alysa LIU     Composition    J4   7.75    1.33       8.43
4   Alysa LIU     Composition    J5   8.75    1.33       8.43
5   Alysa LIU     Composition    J6   8.25    1.33       8.43
6   Alysa LIU     Composition    J7   8.25    1.33       8.43
7   Alysa LIU     Composition    J8   8.50    1.33       8.43
8   Alysa LIU     Composition    J9   8.50    1.33       8.43
9   Alysa LIU    Presentation    J1   9.00    1.33       8.68
10  Alysa LIU    Presentation    J2   9.25    1.33       8.68
11  Alysa LIU    Presentation    J3   8.50    1.33       8.68
12  Alysa LIU    Presentation    J4   8.50    1.33       8.68
13  Alysa LIU    Presentation    J5   9.00    1.33       8.68
14  Alysa LIU    Presentation    J6   8.50    1.33       8.68
15  Alysa LIU    Presentation    J7   8.50    1.33       8.68
16  Alysa LIU    Presentation    J8   8.50    1.33       8.68
17  Alysa LIU    Presentation    J9   8.75    1.33       8.68
18  Alysa LIU  Skating Skills    J1   8.75    1.33       8.29
19  Alysa LIU  Skating Skills    J2   8.50    1.33       8.29
20  Alysa LIU  Skating Skills    J3   8.00    1.33       8.29
21  Alysa LIU  Skating Skills    J4   7.75    1.33       8.29
22  Alysa LIU  Skating Skills    J5   8.50    1.33       8.29
23  Alysa LIU  Skating Skills    J6   8.25    1.33       8.29
24  Alysa LIU  Skating Skills    J7   8.25    1.33       8.29
25  Alysa LIU  Skating Skills    J8   8.25    1.33       8.29
26  Alysa LIU  Skating Skills    J9   8.25    1.33       8.29

In [73]:
# This is in long format, lets get it in wide format
pcs_wide = pcs_df.pivot_table(index=['Skater', 'Component'],columns='Judge',values='Score').reset_index()
panel_avg = pcs_df.groupby(['Skater', 'Component'])['Panel Avg'].first().reset_index()
pcs_wide = pcs_wide.merge(panel_avg, on=['Skater', 'Component'])

pcs_wide.loc[pcs_wide['Skater']=='Alysa LIU',:]

,Skater,Component,J1,J2,J3,J4,J5,J6,J7,J8,J9,Panel Avg
6,Alysa LIU,Composition,9.00,8.50,8.25,7.75,8.75,8.25,8.25,8.50,8.50,8.43
7,Alysa LIU,Presentation,9.00,9.25,8.50,8.50,9.00,8.50,8.50,8.50,8.75,8.68
8,Alysa LIU,Skating Skills,8.75,8.50,8.00,7.75,8.50,8.25,8.25,8.25,8.25,8.29

In [74]:
# Why is Alysa Liu in 6th?? She should be first -- sort should be false
pcs_wide = pcs_df.pivot_table(index=['Skater', 'Component'],columns='Judge',values='Score',sort = False)
panel_avg = pcs_df.groupby(['Skater', 'Component'])['Panel Avg'].first()
pcs_wide = pcs_wide.assign(Panel_Avg=panel_avg)

#Let's try this again:
pcs_wide.head()

Judge                        J1    J2    J3    J4    J5    J6    J7    J8  \
Skater     Component
Alysa LIU  Composition     9.00  8.50  8.25  7.75  8.75  8.25  8.25  8.50
           Presentation    9.00  9.25  8.50  8.50  9.00  8.50  8.50  8.50
           Skating Skills  8.75  8.50  8.00  7.75  8.50  8.25  8.25  8.25
Mone CHIBA Composition     8.50  8.25  8.50  8.25  8.25  8.75  8.50  9.00
           Presentation    8.50  8.75  8.50  8.25  8.50  8.75  8.25  9.00

Judge                        J9  Panel_Avg
Skater     Component
Alysa LIU  Composition     8.50       8.43
           Presentation    8.75       8.68
           Skating Skills  8.25       8.29
Mone CHIBA Composition     8.50       8.46
           Presentation    8.50       8.54

In [88]:
# This is exactly what we should see for each skater!
# Let's group the same for the elements df
elements_wide = elements_df.pivot_table(index=['Skater','Element #','Element'],values=['Base Value','GOE','Final Score'])
elements_wide

                              Base Value  Final Score   GOE
Skater     Element # Element
Ahsun YUN  2         2A             3.30         2.31 -0.99
           3         FCSp4          3.20         3.47  0.27
           5         CCoSp3V        2.25         2.35  0.10
           6         StSq4          3.90         4.07  0.17
           7         LSp3           2.40         2.67  0.27
...                                  ...          ...   ...
Xiangyi AN 2         2A             3.30         3.68  0.38
           3         FCSp4          3.20         3.75  0.55
           5         LSp3           2.40         2.91  0.51
           6         StSq3          3.30         3.58  0.28
           7         CCoSp2         2.50         2.68  0.18

[180 rows x 3 columns]

In [89]:
# Yes, this is exactly what we should have :)

In [ ]:
D