**In this notebook, we will be concatenating the made csv files together**

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read the csv files:
Allen_MenFS_Elements = pd.read_csv('2024_AllenComp_MenFS_Elements.csv')
Allen_MenFS_PCS = pd.read_csv('2024_AllenComp_MenFS_PCS.csv')
Allen_WomenFS_Elements = pd.read_csv('2024_AllenComp_WomenFS_Elements.csv')
Allen_WomenFS_PCS = pd.read_csv('2024_AllenComp_WomenFS_PCS.csv')

Canada_MenFS_Elements = pd.read_csv('2024_Canada_MenFS_Elements.csv')
Canada_MenFS_PCS = pd.read_csv('2024_Canada_MenFS_PCS.csv')
Canada_WomenFS_Elements = pd.read_csv('2024_Canada_WomenFS_Elements.csv')
Canada_WomenFS_PCS = pd.read_csv('2024_Canada_WomenFS_PCS.csv')

France_MenFS_Elements = pd.read_csv('2024_France_MenFS_Elements.csv')
France_MenFS_PCS = pd.read_csv('2024_France_MenFS_PCS.csv')
France_WomenFS_Elements = pd.read_csv('2024_France_WomenFS_Elements.csv')
France_WomenFS_PCS = pd.read_csv('2024_France_WomenFS_PCS.csv')

Japan_MenFS_Elements = pd.read_csv('2024_Japan_MenFS_Elements.csv')
Japan_MenFS_PCS = pd.read_csv('2024_Japan_MenFS_PCS.csv')
Japan_WomenFS_Elements = pd.read_csv('2024_Japan_WomenFS_Elements.csv')
Japan_WomenFS_PCS = pd.read_csv('2024_Japan_WomenFS_PCS.csv')

GPFinal_MenFS_Elements = pd.read_csv('2024_GPFinal_MenFS_Elements.csv')
GPFinal_MenFS_PCS = pd.read_csv('2024_GPFinal_MenFS_PCS.csv')
GPFinal_WomenFS_Elements = pd.read_csv('2024_GPFinal_WomenFS_Elements.csv')
GPFinal_WomenFS_PCS = pd.read_csv('2024_GPFinal_WomenFS_PCS.csv')

In [3]:
# Adding a country/comp and a gender column to each

# function first
def add_metadata(df, gender, competition):
    df["Gender"] = gender
    df["Competition"] = competition
    df["Season"] = "2024"
    df["Segment"] = "Free Skate"
    return df

Allen_MenFS_Elements = add_metadata(Allen_MenFS_Elements, "Men", "Allen")
Allen_MenFS_PCS = add_metadata(Allen_MenFS_PCS, "Men", "Allen")

Allen_WomenFS_Elements = add_metadata(Allen_WomenFS_Elements, "Women", "Allen")
Allen_WomenFS_PCS = add_metadata(Allen_WomenFS_PCS, "Women", "Allen")

Canada_MenFS_Elements = add_metadata(Canada_MenFS_Elements, "Men", "Canada")
Canada_MenFS_PCS = add_metadata(Canada_MenFS_PCS, "Men", "Canada")

Canada_WomenFS_Elements = add_metadata(Canada_WomenFS_Elements, "Women", "Canada")
Canada_WomenFS_PCS = add_metadata(Canada_WomenFS_PCS, "Women", "Canada")

France_MenFS_Elements = add_metadata(France_MenFS_Elements, "Men", "France")
France_MenFS_PCS = add_metadata(France_MenFS_PCS, "Men", "France")

France_WomenFS_Elements = add_metadata(France_WomenFS_Elements, "Women", "France")
France_WomenFS_PCS = add_metadata(France_WomenFS_PCS, "Women", "France")

Japan_MenFS_Elements = add_metadata(Japan_MenFS_Elements, "Men", "Japan")
Japan_MenFS_PCS = add_metadata(Japan_MenFS_PCS, "Men", "Japan")

Japan_WomenFS_Elements = add_metadata(Japan_WomenFS_Elements, "Women", "Japan")
Japan_WomenFS_PCS = add_metadata(Japan_WomenFS_PCS, "Women", "Japan")

GPFinal_MenFS_Elements = add_metadata(GPFinal_MenFS_Elements, "Men", "GPFinal")
GPFinal_MenFS_PCS = add_metadata(GPFinal_MenFS_PCS, "Men", "GPFinal")

GPFinal_WomenFS_Elements = add_metadata(GPFinal_WomenFS_Elements, "Women", "GPFinal")
GPFinal_WomenFS_PCS = add_metadata(GPFinal_WomenFS_PCS, "Women", "GPFinal")

In [4]:
# Let's check to see if this was done correctly
GPFinal_WomenFS_Elements.head()

,Skater,Element #,Element,Base Value,Final Score,GOE,Gender,Competition,Season,Segment
0,Amber GLENN,1,3A,8.0,9.83,1.83,Women,GPFinal,2024,Free Skate
1,Amber GLENN,10,StSq3,3.3,4.05,0.75,Women,GPFinal,2024,Free Skate
2,Amber GLENN,11,ChSq1,3.0,4.21,1.21,Women,GPFinal,2024,Free Skate
3,Amber GLENN,12,LSp4,2.7,3.32,0.62,Women,GPFinal,2024,Free Skate
4,Amber GLENN,2,3F+3T,9.5,10.71,1.21,Women,GPFinal,2024,Free Skate

In [5]:
# Now we can create the master datasets:

all_elements = pd.concat([
    Allen_MenFS_Elements,
    Allen_WomenFS_Elements,
    Canada_MenFS_Elements,
    Canada_WomenFS_Elements,
    France_MenFS_Elements,
    France_WomenFS_Elements,
    Japan_MenFS_Elements,
    Japan_WomenFS_Elements,
    GPFinal_MenFS_Elements,
    GPFinal_WomenFS_Elements
])

all_pcs = pd.concat([
    Allen_MenFS_PCS,
    Allen_WomenFS_PCS,
    Canada_MenFS_PCS,
    Canada_WomenFS_PCS,
    France_MenFS_PCS,
    France_WomenFS_PCS,
    Japan_MenFS_PCS,
    Japan_WomenFS_PCS,
    GPFinal_MenFS_PCS,
    GPFinal_WomenFS_PCS
])

In [6]:
all_elements

,Skater,Element #,Element,Base Value,Final Score,GOE,Gender,Competition,Season,Segment
0,Deniss VASILJEVS,10,FCCoSp4,3.5,4.75,1.25,Men,Allen,2024,Free Skate
1,Deniss VASILJEVS,11,FSSp4,3.0,3.94,0.94,Men,Allen,2024,Free Skate
2,Deniss VASILJEVS,12,ChSq1,3.0,4.71,1.71,Men,Allen,2024,Free Skate
3,Deniss VASILJEVS,2,3Lz+3T,10.1,11.79,1.69,Men,Allen,2024,Free Skate
4,Deniss VASILJEVS,3,3A+2A+SEQ,11.3,11.99,0.69,Men,Allen,2024,Free Skate
...,...,...,...,...,...,...,...,...,...,...
44,Wakaba HIGUCHI,2,3Lz+3T,10.1,11.62,1.52,Women,GPFinal,2024,Free Skate
45,Wakaba HIGUCHI,3,3Lo,4.9,5.88,0.98,Women,GPFinal,2024,Free Skate
46,Wakaba HIGUCHI,4,CCoSp4,3.5,4.20,0.70,Women,GPFinal,2024,Free Skate
47,Wakaba HIGUCHI,5,2S,1.3,1.30,0.00,Women,GPFinal,2024,Free Skate
48,Wakaba HIGUCHI,6,ChSq1,3.0,3.86,0.86,Women,GPFinal,2024,Free Skate

In [7]:
all_pcs

,Skater,Component,J1,J2,J3,J4,J5,J6,J7,J8,J9,Panel_Avg,Gender,Competition,Season,Segment
0,Kevin AYMOZ,Composition,9.00,9.00,9.25,8.50,9.00,9.50,9.25,9.50,9.50,9.21,Men,Allen,2024,Free Skate
1,Kevin AYMOZ,Presentation,9.25,9.00,9.50,8.75,9.50,9.25,9.50,9.50,9.50,9.36,Men,Allen,2024,Free Skate
2,Kevin AYMOZ,Skating Skills,9.00,8.75,9.25,9.00,9.50,8.75,8.75,9.00,9.50,9.04,Men,Allen,2024,Free Skate
3,Ilia MALININ,Composition,8.75,8.75,8.75,8.75,8.75,9.00,9.50,9.00,8.75,8.82,Men,Allen,2024,Free Skate
4,Ilia MALININ,Presentation,8.50,8.50,9.00,8.75,8.75,9.25,9.50,9.25,8.75,8.89,Men,Allen,2024,Free Skate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,Hana YOSHIDA,Presentation,7.25,8.00,8.00,8.00,8.00,7.75,8.50,8.00,8.00,7.96,Women,GPFinal,2024,Free Skate
14,Hana YOSHIDA,Skating Skills,7.75,8.00,8.25,8.00,7.75,8.00,8.50,8.25,8.50,8.11,Women,GPFinal,2024,Free Skate
15,Rino MATSUIKE,Composition,7.75,8.00,8.25,7.50,8.25,7.50,8.25,7.75,8.75,7.96,Women,GPFinal,2024,Free Skate
16,Rino MATSUIKE,Presentation,8.25,8.25,8.25,7.75,8.00,7.75,8.00,7.50,8.25,8.04,Women,GPFinal,2024,Free Skate
17,Rino MATSUIKE,Skating Skills,8.00,8.00,8.75,7.75,8.25,8.00,8.00,8.00,8.25,8.07,Women,GPFinal,2024,Free Skate

In [12]:
all_elements.to_csv('all_elements.csv')

In [13]:
all_pcs.to_csv('all_pcs.csv')